var annotated_dup =
[
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "Color", "struct_color.html", null ],
    [ "Core", "class_core.html", "class_core" ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "HSVColor", "struct_h_s_v_color.html", "struct_h_s_v_color" ],
    [ "Input", "class_input.html", "class_input" ],
    [ "Line", "class_line.html", "class_line" ],
    [ "Mesh", "class_mesh.html", "class_mesh" ],
    [ "Noise", "class_noise.html", "class_noise" ],
    [ "PixelBuffer", "struct_pixel_buffer.html", "struct_pixel_buffer" ],
    [ "Point_t", "class_point__t.html", "class_point__t" ],
    [ "Polar_t", "class_polar__t.html", "class_polar__t" ],
    [ "Renderer", "class_renderer.html", "class_renderer" ],
    [ "ResourceManager", "class_resource_manager.html", "class_resource_manager" ],
    [ "RGBAColor", "struct_r_g_b_a_color.html", "struct_r_g_b_a_color" ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "Shader", "class_shader.html", "class_shader" ],
    [ "Sprite", "class_sprite.html", "class_sprite" ],
    [ "Text", "class_text.html", "class_text" ],
    [ "Texture", "class_texture.html", "class_texture" ],
    [ "Timer", "class_timer.html", "class_timer" ],
    [ "VectorX_t", "class_vector_x__t.html", "class_vector_x__t" ]
];